timeout: 1200s
##############################################
# MVP用 Cloud Build 設定（最小構成）
# - 目的: backend イメージのビルドと Cloud Run への単純デプロイのみ
# - データ準備や大量のシークレット連携は本ファイルから除外
# - 詳細手順は docs/deployment/cloud_run_firebase_mvp.md を参照
##############################################

steps:
  # Backend Docker image build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform', 'linux/amd64',
      '-f', 'backend/Dockerfile',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gamechat-ai-backend/backend:$BUILD_ID',
      '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gamechat-ai-backend/backend:latest',
      '.'
    ]

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gamechat-ai-backend/backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gamechat-ai-backend/backend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gamechat-ai-backend',
      '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gamechat-ai-backend/backend:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000'
    ]

timeout: 1200s

# 注意: MVPでは環境変数/シークレットは Cloud Run 側の設定で管理してください。
# 例) gcloud run services update gamechat-ai-backend --set-env-vars=UPSTASH_VECTOR_REST_URL=... --update-secrets=BACKEND_OPENAI_API_KEY=...
