steps:
  # 環境変数の設定
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # backend用の環境変数ファイル作成
        echo "ENVIRONMENT=production" > backend/.env.production
        echo "OPENAI_API_KEY=$$OPENAI_API_KEY" >> backend/.env.production
        echo "UPSTASH_VECTOR_REST_URL=$$UPSTASH_VECTOR_REST_URL" >> backend/.env.production
        echo "UPSTASH_VECTOR_REST_TOKEN=$$UPSTASH_VECTOR_REST_TOKEN" >> backend/.env.production
        echo "CORS_ORIGINS=https://gamechat-ai.web.app,https://gamechat-ai.firebaseapp.com" >> backend/.env.production
        
        # Cloud Run用の環境変数ファイル作成（YAML形式）
        cat > cloud-run-env.yaml << EOF
        ENVIRONMENT: production
        LOG_LEVEL: INFO
        CORS_ORIGINS: "https://gamechat-ai.web.app,https://gamechat-ai.firebaseapp.com"
        EOF
    secretEnv: ['OPENAI_API_KEY', 'UPSTASH_VECTOR_REST_URL', 'UPSTASH_VECTOR_REST_TOKEN']

  # バックエンドDockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'backend/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/gamechat-ai-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/gamechat-ai-backend:latest',
      '.'
    ]

  # Container Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gamechat-ai-backend:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gamechat-ai-backend:latest']

  # Cloud Runにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'gamechat-ai-backend',
      '--image', 'gcr.io/$PROJECT_ID/gamechat-ai-backend:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--env-vars-file', 'cloud-run-env.yaml',
      '--update-secrets', 'OPENAI_API_KEY=OPENAI_API_KEY:latest',
      '--update-secrets', 'UPSTASH_VECTOR_REST_URL=UPSTASH_VECTOR_REST_URL:latest',
      '--update-secrets', 'UPSTASH_VECTOR_REST_TOKEN=UPSTASH_VECTOR_REST_TOKEN:latest'
    ]
    env:
      - 'CLOUDSDK_RUN_REGION=asia-northeast1'

# ビルドのタイムアウト設定
timeout: 1200s

# シークレットの設定
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest
      env: OPENAI_API_KEY
    - versionName: projects/$PROJECT_ID/secrets/UPSTASH_VECTOR_REST_URL/versions/latest
      env: UPSTASH_VECTOR_REST_URL
    - versionName: projects/$PROJECT_ID/secrets/UPSTASH_VECTOR_REST_TOKEN/versions/latest
      env: UPSTASH_VECTOR_REST_TOKEN

# ビルドオプション
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
