apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://gamechat-ai-backend-507618950161.asia-northeast1.run.app","https://gamechat-ai-backend-2u5fbys56q-an.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-northeast1
  name: gamechat-ai-backend
  namespace: '507618950161'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 525.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: xhtmeprsrk
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: CORS_ORIGINS
          value: https://gamechat-ai.web.app,https://gamechat-ai.firebaseapp.com,http://localhost:3000
        image: gcr.io/gamechat-ai-production/gamechat-ai-backend:latest
        ports:
        - containerPort: 8000
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8000
          timeoutSeconds: 240
      serviceAccountName: 507618950161-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - percent: 100
    revisionName: gamechat-ai-backend-00003-v9j
