name: 🧪 Test追加・修正
description: テストコードの追加や修正に関するIssue
title: "[test] "
labels: ["test"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: このIssueで追加・修正するテストの内容を記載してください。
      placeholder: 例：APIのユニットテストを追加する
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 実装タスク
      description: 実装に必要な作業を箇条書きで記載してください。
      placeholder: |
        - [ ] テストケースの洗い出し
        - [ ] テストコードの実装
        - [ ] テストの実行と確認
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 備考
      description: その他の注意事項や参考リンクがあれば記載してください。
      placeholder: 任意
    validations:
      required: false