name: Label issues by title

on:
  issues:
    types: [opened, edited]

jobs:
  label-by-title:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on issue title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();

            const labels = [];
            if (title.startsWith('[feature]')) {
              labels.push('feature');
            } else if (title.startsWith('[bug]')) {
              labels.push('bug');
            } else if (title.startsWith('[test]')) {
              labels.push('test');
            } else if (title.startsWith('[chore]')) {
              labels.push('chore');
            } else if (title.startsWith('[fix]')) {
              labels.push('fix');
            } else if (title.startsWith('[refactor]')) {
              labels.push('refactor');
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              });
            }
